create table Author (
	id integer generated by default as identity,
	name varchar(255),
	primary key (id)
);

create table Book (
	id integer generated by default as identity,
	publicationDate timestamp,
	subtitle varchar(255),
	title varchar(255),
	primary key (id)
);

create table Book_Author (
	Book_id integer not null,
	authors_id integer not null,
	primary key (Book_id, authors_id)
);

alter table Book_Author
	add constraint FKt42qaxhbq87yfijncjfrs5ukc
	foreign key (authors_id)
	references Author;

alter table Book_Author
	add constraint FKsbb54ii8mmfvh6h2lr0vf2r7f
	foreign key (Book_id)
	references Book;

insert into Book (id, title, subtitle, publicationDate) values (1, 'Hibernate入門', 'JPAModelGen、MetaModel、QueryDsl、Criteria API、HQL、Envers、Spring Framework、JMS/MQトランザクション対応', '2008-08-07');

insert into Author (id, name) values (1, '船木 健児');
insert into Author (id, name) values (2, '三田 淳一');
insert into Author (id, name) values (3, '佐藤 竜一');

insert into Book_Author (Book_id, authors_id) values (1, 1);
insert into Book_Author (Book_id, authors_id) values (1, 2);
insert into Book_Author (Book_id, authors_id) values (1, 3);
